#!/bin/bash

# Check if script is run as root
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root. Please use sudo." >&2
   exit 1
fi

read -p "User to cleanup: " cleanup_username

if [ -z "$cleanup_username" ]; then
  echo "Give username!"
  exit 1
fi

pkill -u $cleanup_username
chattr -i /home/$cleanup_username/arisu
userdel -r $cleanup_username
