#!/bin/bash

# Auto-elevate with sudo if not already root
if [[ $EUID -ne 0 ]]; then
   echo "Elevating with sudo..."
   exec sudo "$0" "$@"
fi

if [ $# -lt 1 ]; then
  echo "Usage: $0 <username>" >&2
  exit 1
fi
cleanup_username="$1"

if [ -z "$cleanup_username" ]; then
  echo "Give username!"
  exit 1
fi

pkill -u $cleanup_username
chattr -i /home/$cleanup_username/arisu
userdel -r $cleanup_username
